---
- name: Install Docker and run the application
  hosts: app
  become: true
  tasks:
    - name: Install necessary system packages
      apt:
        pkg:
        - python3-pip
        state: latest
        update_cache: true
        
    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Install Docker SDK for Python
      pip:
        name: docker
        state: present
        executable: pip3

    - name: Add current user to the docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Pull the Django Docker image
      docker_image:
        name: "{{ docker_image }}"
        tag: latest
        source: pull

    - name: Run Docker container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image }}"
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "{{ host_port }}:{{ container_port }}"
