---
- name: Setup Nginx on web servers
  hosts: web
  become: true
  roles:
    - nginx

- name: Install Docker and run the application
  hosts: app
  become: true
  roles:
    - Docker
  tasks:
    - name: Install necessary system packages
      apt:
        pkg:
        - python3-pip
        state: latest
        update_cache: true

    - name: Install Docker SDK for Python
      pip:
        name: docker
        state: present
        executable: pip3

    - name: Pull the Django Docker image
      docker_image:
        name: "{{ docker_image }}"
        tag: latest
        source: pull

    - name: Run Docker container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image }}"
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "{{ host_port }}:{{ container_port }}"
        volumes:
          - "{{ django_host_static_path }}:{{ django_static_path }}"
